apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata: frond-pod
      labels:
        app: front-app
    spec:
      containers:
        - name: front-con
          image: yunchae02/front:1
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
